config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :meets
      resources :my_unavailabilities
      get 'my_bookings' => 'meets#my_bookings', as: :my_bookings
      root to: 'meets#index'
    end

  resources :meets, except: [:edit, :update]
  get 'my_bookings' => 'meets#my_bookings', as: :my_bookings

  # get '/calendars', to: 'meets#calendars', as: 'calendars'
  # get '/redirect', to: 'meets#redirect', as: 'redirect'
  # get '/callback', to: 'meets#callback', as: 'callback'
  # get '/events/:calendar_id', to: 'meets#events', as: 'events', calendar_id: /[^\/]+/
  # post '/events/:calendar_id', to: 'meets#new_event', as: 'new_event', calendar_id: /[^\/]+/

  devise_for :users

  root to: 'meets#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meet.rb
class Meet < ApplicationRecord
  belongs_to :user
  validates :date, presence:true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :meets, dependent: :destroy
  validates :first_name, :last_name, presence:true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/me_controller.rb
class Admin::MeController < ApplicationController

  def show
    @meet = Meet.find(params[:id])
  end

  def new
    @meet = Meet.new
  end

  def create
    @meet = Meet.new(meet_params)
    @meet.save
    redirect_to meet_path
  end

  def edit
    @meet = Meet.find(params[:id])
  end

  def update
    @meet = Meet.new(meet_params)
    @meet.update(meet_params)
    redirect_to meet_path
  end

  def destroy
    @meet = Meet.find(params[:id])
    @meet.destroy
    redirect_to meet_path
  end
end

app/controllers/admin/meets_controller.rb
class Admin::MeetsController < ApplicationController
before_action :require_admin

  def index

    @meets= Meet.all
  end

  def my_bookings
    @meets = Meet.all
  end

  def show
    @meet = Meet.find(params[:id])

  end

  def new
    @meet = Meet.new
  end

  def create
    @meet = Meet.new(meet_params)
    @meet.user = current_user
    if @meet.save
      redirect_to admin_my_bookings_path
    else
      render :new
    end
  end

  def edit
    @meet = Meet.find(params[:id])
  end

  def update
    @meet = Meet.find(params[:id])
    @meet.update(meet_params)
    redirect_to [:admin,@meet]
  end

  def destroy
    @meet = Meet.find(params[:id])
    @meet.destroy
    redirect_to admin_my_bookings_path
  end

  private

  def meet_params
    params.require(:meet).permit(:date, :first_name, :last_name)
  end

  def require_admin
    unless current_user.admin?
    redirect_to meets_path
    end
  end
end

app/controllers/admin/my_unavailabilities_controller.rb
class Admin::MyUnavailabilitiesController < ApplicationController
before_action :require_admin

  def index
    @meets = Meet.all
  end

  def show
    @meet = Meet.find(params[:id])
  end

  def new
    @meet = Meet.new
  end

  def create
    @meet = Meet.new(meet_params)
    @meet.user = current_user
    if @meet.save
      redirect_to admin_my_unavailabilities_path
    else
      render :new
    end

  end

  def edit
    @meet = Meet.find(params[:id])
  end

  def update
    @meet = Meet.new(meet_params)
    @meet.update(meet_params)
    redirect_to admin_my_unavailability_path
  end

  def destroy
    @meet = Meet.find(params[:id])
    @meet.destroy
    redirect_to admin_my_unavailabilities_path
  end

  private

  def meet_params
    params.require(:meet).permit(:date, :reason)
  end

  def require_admin
    unless current_user.admin?
    redirect_to meets_path
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end

end

app/controllers/meets_controller.rb
class MeetsController < ApplicationController

  def index
    @meets = Meet.all

  end

  def my_bookings
  @meets = current_user.meets
  end

  def show
    @meet = Meet.find(params[:id])
  end

  def new
    @meet = Meet.new
  end

  def create
    @meet = Meet.new(meet_params)
    @meet.user = current_user
    if @meet.save
      redirect_to my_bookings_path
    else
      render :new
   end
  end

  def destroy
    @meet = Meet.find(params[:id])
    @meet.destroy
    redirect_to my_bookings_path
  end

  private

  def meet_params
    params.require(:meet).permit(:date)
  end


 #  def client_options
 #   {
 #     client_id: ENV["google_client_id"],
 #     client_secret: ENV["google_client_secret"],
 #     authorization_uri: 'https://accounts.google.com/o/oauth2/auth',
 #     token_credential_uri: 'https://accounts.google.com/o/oauth2/token',
 #     scope: Google::Apis::CalendarV3::AUTH_CALENDAR,
 #     redirect_uri: callback_url
 #   }
 # end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/googlecalendar.rb
require 'googleauth'
require 'google/apis/calendar_v3'

class GoogleCalendarHelper

  attr_reader :calendar
  SCOPE = ["https://www.googleapis.com/auth/calendar"]
  CALENDAR_ID = 'drm9c74h2j24fo1e709ct1l90s@group.calendar.google.com'

  def initialize
	@calendar = Google::Apis::CalendarV3::CalendarService.new
	# get_application_default forces the use of this environment variable.
	# Set it to the location of your JSON credentials.
	ENV["GOOGLE_APPLICATION_CREDENTIALS"]
	@calendar.authorization = Google::Auth.get_application_default(SCOPE)
  end
end

app/views/admin/meets/edit.html.erb
<div class="corps">

    <h1>Modifier un Rendez-vous</h1>
      <%= simple_form_for [:admin,@meet] do |f| %>

        <%= f.input :first_name%>
        <%= f.input :last_name%>
        <%= f.input :date%>
        <%= f.button :submit, "Modifier cette séance", class: "btn btn-danger mt-4 mb-3 w-30 text-center", id: "cancel" %>

      <% end %>

</div>

app/views/admin/meets/index.html.erb
<div class="corps">
  <div class="text-center">
    <h1>Calendrier</h1>
  </div>


      <div class= " justify-content d-flex">
        <%= link_to "Prendre un rdv", new_admin_meet_path, class: "btn
        btn-primary ml-5 mr-5 w-50", id: "take" %>
        <%= link_to "Ajouter une indisponibilité", new_admin_my_unavailability_path,  class: "btn
        btn-warning ml-5 mr-5 w-50", id: "cancel" %>
      </div>



</div>

app/views/admin/meets/my_bookings.html.erb
<div class="corps">
  <h1>Mes rendez-vous</h1>
  <div class="text-center">
    <%= link_to "Prendre un autre rdv", new_admin_meet_path, class: "btn btn-primary mt-4 mb-3 w-30 text-center", id: "take" %>
  </div>
  <h3 class="text-center"> Voici la liste des rendez-vous que vous avez.</h3>
  <% @meets.each do |meet| %>
    <% if meet.reason.nil? %>
      <div class="button w-50 mx-auto">
        <%= link_to admin_meet_path(meet.id), class:"bookings" do %>
            <h4 class="text-center">
              <% if current_user.first_name == meet.user.first_name && current_user.last_name == meet.user.last_name %>
                <%= meet.first_name %> <%= meet.last_name %>
              <% else %>
                <%= meet.user.first_name %> <%= meet.user.last_name %>
              <% end %>
            </h4>
            <p class="text-center"><%= meet.date %></p>
          <% end %>
        </div>
    <% end %>
  <% end %>
</div>

app/views/admin/meets/new.html.erb
<div class="corps">

    <h1>Prendre un Rendez-vous</h1>
      <%= simple_form_for @meet, url: admin_meets_path do |f| %>

        <%= f.input :first_name%>
        <%= f.input :last_name%>
        <%= f.input :date%>
        <%= f.button :submit, "Réserver cette séance", class: "btn btn-primary mt-4 mb-3 w-30 text-center", id: "take" %>

      <% end %>

</div>

app/views/admin/meets/show.html.erb
<div class="corps">

  <div class="text-center">
    <h1>Mon rendez-vous du</h1>
  </div>


      <div class="button">
          <h2>
            <% if current_user.first_name == @meet.user.first_name && current_user.last_name == @meet.user.last_name %>
              <%= @meet.first_name %> <%= @meet.last_name %>
            <% else %>
              <%= @meet.user.first_name %> <%= @meet.user.last_name %>
            <% end %>
          </h2>
          <h3><%= @meet.date %></h3>
        <div class= "d-flex">
          <%= link_to "Annuler", admin_meet_path(@meet.id), method: :delete, class: "btn
          btn-danger ml-5 mr-5 w-40", id: "cancel", data: { confirm: 'Souhaitez vous vraiment annuler?' } %>
          <%= link_to "Modifier", edit_admin_meet_path(@meet.id), class: "btn
          btn-primary ml-5 mr-5 w-40", id: "take", data: { confirm: 'Souhaitez vous vraiment modifier?' } %>
        </div>
    </div>

</div>

app/views/admin/my_unavailabilities/edit.html.erb
<div class="corps">

    <h1>Modifier une indisponibilité</h1>
      <%= simple_form_for [:admin,@meet] do |f| %>

        <%= f.input :reason %>
        <%= f.input :date%>
        <%= f.button :submit, "Modifier votre indisponibilité", class: "btn btn-danger mt-4 mb-3 w-30 text-center", id: "cancel" %>

      <% end %>

</div>

app/views/admin/my_unavailabilities/index.html.erb
<div class="corps">
  <h1>Mes indisponibilités</h1>
  <div class="text-center">
    <%= link_to "Ajouter une indisponibilité", new_admin_my_unavailability_path, class: "btn btn-warning mt-4 mb-3 w-30 text-center", id: "cancel" %>
  </div>
  <h3 class="text-center"> Vous ne pourrez pas être là durant la période du :</h3>
  <% @meets.each do |meet| %>
    <% if !meet.reason.nil?%>
      <div class="button w-50 mx-auto">
      <%= link_to admin_my_unavailability_path(meet.id), class:"bookings" do %>
            <h4 class="text-center">
              <%= meet.date %>
            </h4>
            <p class="text-center"> <%= meet.reason%> </p>
      </div>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/admin/my_unavailabilities/new.html.erb
<div class="corps">

    <h1>Indisponible du</h1>
      <%= simple_form_for @meet, url: admin_my_unavailabilities_path do |f| %>

        <%= f.input :reason %>
        <%= f.input :date%>
        <%= f.button :submit, "Ajouter une indisponibilité", class: "btn btn-warning mt-4 mb-3 w-30 text-center", id: "cancel" %>

      <% end %>

</div>

app/views/admin/my_unavailabilities/show.html.erb
<div class="corps">

  <div class="text-center">
    <h1>Je ne suis pas disponible du</h1>
  </div>


      <div class="button">
        <h2><%= @meet.date %></h2>
        <div class= "d-flex">
          <%= link_to "Annuler", admin_my_unavailability_path(@meet.id), method: :delete, class: "btn
          btn-danger ml-5 mr-5 w-30", id: "cancel", data: { confirm: 'Souhaitez vous vraiment annuler?' } %>
          <%= link_to "Modifier", edit_admin_my_unavailability_path(@meet.id), class: "btn
          btn-primary ml-5 mr-5 w-30", id: "take", data: { confirm: 'Souhaitez vous vraiment modifier?' } %>
        </div>
      </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= favicon_link_tag 'logo.png' %>
    <meta name="description" content="description">
    <meta name="image" content="logo.png">

    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>

  </body>
</html>

app/views/meets/calendars.html.erb
<div class="corps">
  <div class="text-center">
    <h1>Calendrier</h1>
  </div>
  <div clas="mx-auto">



<iframe src="https://calendar.google.com/calendar/embed?showTitle=0&amp;showPrint=0&amp;showTabs=0&amp;showCalendars=0&amp;showTz=0&amp;mode=WEEK&amp;height=800&amp;wkst=2&amp;bgcolor=%23339999&amp;src=g5ihq6khvg460jleb6upqlt9pg%40group.calendar.google.com&amp;color=%23875509&amp;ctz=Europe%2FParis" style="border-width:0" width="1200" height="800" frameborder="0" scrolling="no"></iframe>

    


  <%= link_to "Prendre un rdv", new_meet_path, class: "btn btn-primary text-center", id: "take" %>
  </div>
</div>

app/views/meets/index.html.erb
<div class="corps">
  <div class="text-center">
    <h1>Calendrier</h1>
  </div>
  <div clas="mx-auto">



<iframe src="https://calendar.google.com/calendar/embed?showTitle=0&amp;showPrint=0&amp;showTabs=0&amp;showCalendars=0&amp;showTz=0&amp;mode=WEEK&amp;height=800&amp;wkst=2&amp;bgcolor=%23339999&amp;src=g5ihq6khvg460jleb6upqlt9pg%40group.calendar.google.com&amp;color=%23875509&amp;ctz=Europe%2FParis" style="border-width:0" width="1200" height="800" frameborder="0" scrolling="no"></iframe>

    


  <%= link_to "Prendre un rdv", new_meet_path, class: "btn btn-primary text-center", id: "take" %>
  </div>
</div>

app/views/meets/my_bookings.html.erb
<div class="corps">
  <h1>Mes rendez-vous</h1>
  <div class="text-center">
    <%= link_to "Prendre un autre rdv", new_meet_path, class: "btn btn-primary mt-4 mb-3 w-30 text-center", id: "take" %>
  </div>
  <h3 class="text-center"> Voici la liste des rendez-vous que vous avez.</h3>
  <% @meets.each do |meet| %>
    <%= link_to meet_path(meet.id), class:"bookings" do %>
    	<div class="button w-50 mx-auto">
          <h4 class="text-center">
            <%= meet.date %>
         </h4>
     </div>
    <% end %>
  <% end %>
</div>

app/views/meets/new.html.erb
<div class="corps">

    <h1>Prendre un Rendez-vous</h1>
      <%= simple_form_for @meet, url: meets_path do |f| %>

    
        <%= f.input :date%>
        <%= f.button :submit, "Réserver cette séance", class: "btn btn-primary mt-4 mb-3 w-30 text-center", id: "take" %>

      <% end %>

</div>

app/views/meets/show.html.erb
<div class="text-center">
  <h1>Mon rendez-vous du</h1>
</div>


  <div class="button">
    <p><%= @meet.date %></p>
    <%= link_to "Annuler", meet_path(@meet.id), method: :delete, class: "btn
    btn-danger", id: "cancel", data: { confirm: 'Souhaitez vous vraiment annuler?' } %>
  </div>

app/views/pages/home.html.erb
<h1>Calendrier Google</h1>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div id="bg">
  <ul>

    <li>
      <% if current_user && current_user.admin? %>
      <%= link_to "Calendrier", admin_root_path  %>
      <% else %>
      <%= link_to "Calendrier", root_path  %>
      <% end %>
      </li>

    <% if current_user && current_user.admin? %>
      <li>
        <%= link_to "Mes Indisponibilités", admin_my_unavailabilities_path%>
      </li>
    <%end%>

    <li>
        <% if current_user && current_user.admin? %>
        <%= link_to "Mes Rendez-Vous", admin_my_bookings_path  %>
        <% else %>
        <%= link_to "Mes Rendez-Vous", my_bookings_path  %>
        <%end %>
      </li>

      <li>
        <%= link_to "Mon Profil", edit_user_registration_path %>
      </li>


    <li>
        <% if user_signed_in? %>
        <%= link_to t(".sign_out", default: "Déconnecter"), destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to t(".sign_in", default: "Se Connecter"), new_user_session_path %>
      <% end %>
    </li>
  </ul>
</div>